name: Hellow-world

on:
  push:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: show node version
        run: echo node -v

      - name: instamm dependencies
        run: npm install

      - name: build the app
        run: npm run build